server:
  port: 8081
  servlet:
    encoding:
      force: true
spring:
  datasource:
    url: jdbc:mysql://42.192.133.167:3306/task?useSSL=false&serverTimezone=GMT%2B8
    username: administrator
    password: administrator
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 465
    username: 1829385036@qq.com
    password: cysgfxedpeqcccfc
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactor
          auth: true
          starttls:
            enable: true
          stattls:
            required: true
          ssl:
            enable: true
        debug: true
    protocol: smtp
logging:
  level:
    com.task: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
