server:
  port: 80
  servlet:
    encoding:
      force: true
spring:
  datasource:
    url: jdbc:mysql://42.192.133.167:3306/task?useSSL=false&serverTimezone=GMT%2B8
    username: administrator
    password: administrator
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.task: debug
